% MATLAB Publish Configurations
% @version 1
% It is recommended that you do not edit this file directly, but use the
% Configuration Editor provided in MATLAB. Changes made to comments that
% exist outside of a configuration will not be saved.

%% @name Factory Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

%% @name User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

%% @name ece532_h9_conrad
%  @associatedFile C:\Users\ben\ece532\h9\ece532_h9_conrad.m
%  @mostRecentlyActioned true
%  @uniqueId 41cec553:155e528acd9:-7fff
%  @publishOptionsBasedOn User Default

publish_options.outputFileFormat='pdf';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;
publish_options.codeToEvaluate=[ ...
'% Modify expression to add input arguments.' char(10) ...
'% Example:' char(10) ...
'%   a = [1 2 3; 4 5 6]; ' char(10) ...
'%   foo(a);' char(10) ...
'' char(10) ...
'ece532_h9_conrad' char(10) ...
]

publish('C:\Users\ben\ece532\h9\ece532_h9_conrad.m',publish_options);

